# -*- coding: utf-8 -*-
"""Fifa_2020_Data_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aUpNXgzcoI83DsgSKAIigH4s4rouIXsZ
"""

import pandas as pd
import numpy as np
import seaborn as sb
import csv, os
from matplotlib import pyplot as plt


fifa = pd.read_excel('C:\Users\Aryan\Desktop\Excel Sheets\players_20.csv')

fifa.describe()

fifa.columns

fifa.head()

"""Differnet columns present in dataframe"""

for col in fifa.columns:
  print(col)

fifa.shape

"""Majority of players from one nation?"""

fifa['nationality'].value_counts()

"""Majority of the players are from to England"""

fifa['nationality'].value_counts()[0:10]

"""Bar Plot depicting nationality """

plt.figure(figsize=(8,5))
plt.bar(list(fifa['nationality'].value_counts()[0:5].keys()),list(fifa['nationality'].value_counts()[0:5]),color="g")
plt.show()

"""Salary of the players"""

player_salary = fifa[['short_name', 'wage_eur']]
player_salary.head()

"""Sorting salaries"""

player_salary = player_salary.sort_values(by=['wage_eur'],ascending=False)

player_salary.head()

"""Graph for salaries"""

plt.figure(figsize=(8,5))
plt.bar(list(player_salary['short_name'][0:5]),list(player_salary['wage_eur'])[0:5],color ="b")

"""Analysis of Argentine footballers"""

fifa['nationality'] == 'Argentina'

Argentina = fifa[fifa['nationality']=='Argentina']
Argentina.head()

"""Tallest players of Argentina"""

Argentina.sort_values(by=['height_cm'],ascending=False).head()

Argentina.sort_values(by=['weight_kg'],ascending = False).head()

Argentina[['short_name', 'wage_eur']].sort_values(by=['wage_eur'],ascending=False).head()

plt.figure(figsize=(8,5))
plt.bar(list(Argentina['short_name'][0:5]),list(Argentina['wage_eur'])[0:5],color="r")

"""Best rated Shooting Skills"""

player_shooting = fifa[['short_name', 'shooting']]

player_shooting.sort_values(by = ['shooting'],ascending = False).head()

"""Players playing for FCBarcelona"""

FCB = fifa[fifa['club']=='FC Barcelona']

FCB.sort_values(by=['wage_eur'],ascending=False).head()

FCB['nationality'].value_counts()